<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Iridium.UI</AssemblyName>
    <RootNamespace>Iridium.UI</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Iridium.Protocol\Iridium.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
  </ItemGroup>

</Project>
