<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Iridium.Protocol</AssemblyName>
    <RootNamespace>Iridium.Protocol</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="emoji-test.txt" LogicalName="Iridium.Protocol.emoji-test.txt" />
  </ItemGroup>

</Project>
